---
- name: Remove Java 7 Version
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: Install Java 8 Version
  yum:
    name: java-1.8.0-openjdk
    enablerepo: epel
    state: present

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    baseurl: http://pkg.jenkins.io/redhat
    enabled: no
    gpgcheck: yes

- name: Install Jenkins
  yum:
    name: jenkins-2.107-1.1
    enablerepo: jenkins
    state: present

- name: Get Installed bundle
  git:
    repo: 'https://github.com/tejoyasha/jenkins-base.git'
    dest: /var/lib/jenkins
    version: master

- name: Set the jenkins foler appropriate permissions
  file:
    dest: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    mode: u=rwX,g=rX,o=rX 
    recurse: yes

- name: Start Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started

